version: '2'
volumes:
  db-data:
  redis-data:
  app-storage:
  app-bootstrap:
networks:
  internal:
    internal: true
  external:
    driver: bridge
services:
  app:
    image: zknt/pixelfed
    restart: unless-stopped
    volumes:
      - "app-storage:/var/www/storage"
    depends_on:
      - db
      - redis
    ports:
      - "80:80"
  worker:
    image: zknt/pixelfed
    restart: unless-stopped
    volumes:
      - "app-storage:/var/www/storage"
    entrypoint: /worker-entrypoint.sh
    depends_on:
      - db
      - redis
      - app
  db:
    image: mysql:8.0
    restart: unless-stopped
    networks:
      - internal
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "db-data:/var/lib/mysql"
  redis:
    image: redis:5-alpine
    restart: unless-stopped
    volumes:
      - "redis-data:/data"
    networks:
      - internal
